### ISSUE TITLE
Activate Code checking tools Codacity, Codefactor and Deepscan for OpenPDF

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#1014]
Please activate Codacity, Codefactor and Deepscan for OpenPDF.

https://app.codacy.com/gh/fciv-net/fciv-net/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_grade

https://www.codefactor.io/repository/github/fciv-net/fciv-net

https://deepscan.io/dashboard/#view=project&tid=18818&pid=22102&bid=649871

@asturio

**Comment by asturio** [comment]
@andreasrosdal I'm working on it.

**Comment by andreasrosdal** [comment]
Here's codacy and codefactor on my fork:

https://app.codacy.com/gh/andreasrosdal/openpdf/dashboard

https://www.codefactor.io/repository/github/andreasrosdal/openpdf

**Comment by asturio** [comment]
@andreasrosdal 
Hi Andreas,

I made some changes so, codacy and codefactor are integrated (deepscan seems to be only for JS).

codacy is a little bit complex, because I needed to setup jacoco to run in the GitHub-Workflow (take a look at _.github/workflows/maven.yml_), but I seems to work well. I also put 2 badges in the readme with that info.

codefactor was straightforward, but I think we should observe the if the next PRs are being checked. I don't know if using both codacy and codefactor is not overkill.

You are invited to manage both apps. Let me know, if it works or something is missing.
