### ISSUE TITLE
Java 8 (Java 1.8) support and broken pom since 1.3.37

### ISSUE THREAD

**Issue by Lonzak** [LibrePDF/OpenPDF#1033]
I just tried to update to the latest version of openPDF (currently 1.3.39) however got an error related to the Java version.
I would like to ask for the reason to increase the minimum Java version? 
This is quite a big change for a bugfix version. I didn't expect this from 1.3.36 -> 1.3.37. According to semantic versioning this is a breaking change and should have been version 2.0.0. Was there some newer feature the project wanted to use?

A lot of our customers are still based on Java8 so this means we'll have to continue to maintain our own iText fork. (I already started the migration to openPDF which means full stop now :-(

Additionally I would like to ask whether some other users have a java 8 requirement? 

Side note:
The pom.xml seems broken since 1.3.37:
[WARNING] The POM for com.github.librepdf:openpdf:jar:1.3.37 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by andreasrosdal** [comment]
OpenPDF 1.3.37 requires Java 11 or later. This will allow modernization of the code-base using new features and syntax available in Java 11. Many other common Java libraries have begun to require Java 11 or later. 

If you need to use Java 8 then you can use version 1.3.36 or earlier. If there is a need for more releases of OpenPDF supporting Java 8 then it can considered.

I recommend to begin encouraging your customers to upgrade to Java 11.

**Comment by asturio** [comment]
I'm for updating the version of OpenPDF to 2.0.0 because of that. We could create a new "java8" branch from an appropriate commit (1.3.36?), but this branch would only get bugfixes, but no new features. Keep development for Java 11 for now.

I would link to this page of Eclipse Temurin: https://adoptium.net/de/support/
by now Java 11 and Java 17 will be supported until Oct 2027. So probably we need to make progress updating the java support.

I don't think keeping things in java 8 is a smart choice, even if this version is support until 2026. Everybody needs to move forward, and the only reason to stick with an old version of java, is if the software is also end-of-life.

I suggest paying attention to the version-numbers:

- OpenPDF 1.3, should be compatible with Java 8
- OpenPDF 2.0, should be Java 11 based
- OpenPDF 2.1, should be Java 17 based
- And Java 21 is the latest LTS Version

Not all libraries are now on Java 17, but as the environment (didn't find a better word) reach a certain level, OpenPDF should follow.

**Comment by asturio** [comment]
Closing this now, as there are now different branches for different releases:

- OpenPDF 1.3, Java 8 based (https://github.com/LibrePDF/OpenPDF/tree/1.3-java8)
- OpenPDF 1.4, Java 11 based (https://github.com/LibrePDF/OpenPDF/tree/1.4-java11)
- OpenPDF 2.0, Java 17 based (https://github.com/LibrePDF/OpenPDF/tree/master) - main development here
