### ISSUE TITLE
Help other projects upgrade from iText 2.x to OpenPDF

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#145]
This issue is about helping other open source projects migrating from iText 2.x to OpenPDF, so they can continue using the maintained LGPL/MPL version.

https://github.com/TIBCOSoftware/jasperreports/issues/17
https://github.com/javamelody/javamelody/issues/788
https://github.com/flyingsaucerproject/flyingsaucer/pull/123

Atlassian Confluence:  https://jira.atlassian.com/browse/CONFSERVER-55407

There are other projects here as well:  https://mvnrepository.com/artifact/com.itextpdf/itextpdf

**Comment by srbala** [comment]
flyingsaucer project already has openpdf profile  https://mvnrepository.com/artifact/org.xhtmlrenderer/flying-saucer-pdf-openpdf

https://github.com/nuxeo/nuxeo-signature already using openpdf

**Comment by arnthom** [comment]
OK, I will try to use OpenPDF as a iText 2 replacement ... meanwhile I have been using PdfBoxLayout.

BUT: 
- where is a binary to download? 
- how can I import this into eclipse to build a binary?
- can I use the old code compatible with iText2 or do I have to change things? is there any manual for this scenario?

Thanks a lot!

**Comment by Lonzak** [comment]
1) Binary is available in maven central: https://search.maven.org/search?q=g:com.github.librepdf%20AND%20a:openpdf&core=gav

2) Your 2nd question I don't understand - do you want to build your own binary? This is possible just download it via git and build it using the maven.

3) Just replace the jar and have a look where you get errors...

**Comment by arnthom** [comment]
OK. thanks.
I don't have maven and thought there might be some way to put it into an eclipse project to build the .jar. But jar is available, thanks again.

**Comment by msdobrescu** [comment]
Hi, same problem with Eclipse here.
I don't use Maven, I want to build it myself, but I don't get the main project imported.
I.e., using Eclipse (2019-09), I try to import the project from the sources path, but only the pdf-swing and pdf-toolbox are imported properly, and Eclipse projects are created for them, but for openpdf not.
An empty nuild configuration is created only.
What is the reason?

**Comment by srbala** [comment]
you have to import project as existing maven project and select pom.xml in root folder

![image](https://user-images.githubusercontent.com/1273137/69080694-752c2700-0a0a-11ea-8b92-f06d979a7c32.png)

![image](https://user-images.githubusercontent.com/1273137/69080778-9ab93080-0a0a-11ea-8844-997ba5c75801.png)

![image](https://user-images.githubusercontent.com/1273137/69080830-af95c400-0a0a-11ea-98d6-cc2b02914d0b.png)

**Comment by srbala** [comment]
It's easier to get prebuilt jar from maven repository, unless you  are planning on work on any issues. Master branch points upto date development. If you need stable sources, use release versions https://github.com/LibrePDF/OpenPDF/archive/1.3.11.zip for 1.3.11 release. Prior versions available at https://github.com/LibrePDF/OpenPDF/releases

**Comment by msdobrescu** [comment]
It's simply strange. What is openpdf-parent? Eclipse it's not that friendly in referring projects.
On one hand, importing as Maven, although seems successful, doesn't work for pdf-swing, pdf-toolbox, because claims those can't find openpdf build through Maven. I would have expected to be able to refer openpdf from the local build... Anyway, I probably don't need them, so removing them or ignoring the errors, would make my test project build. Here comes the total disappointment. Eclipse is able to build my test project only if I refer the openpdf project as module. But can't run it, it says it can't find openpdf module. I have worked with Eclipse years ago, now I feel like a total newbie. Or Eclipse is still unfinished here... and can't add the needed runtime params to vm?

**Comment by msdobrescu** [comment]
And to clarify why I have did like this: I need to debug openpdf just to start understanding it and know it better.

**Comment by srbala** [comment]
Looks like you are not familiar with maven and how to compile and build. Please google up, you may find some material. It might takes tedious step using debug in Maven; you may have to use the sources to import into regular java project and set the dependency manually. 

This thread OR project issues is not meant to be how-to

**Comment by msdobrescu** [comment]
Indeed, but Maven is not my choice at all, I should not intall Maven related plugins just to disable/remove it from the project.

**Comment by msdobrescu** [comment]
Hi, I chose Maven, in the end, even in Eclipse. The reason is Eclipse is not that clever at importing OpenPDF. It can't properly import OpenPDF because the parent project is called "OpenPDF" and contains the core project, called "openpdf" , that name being in conflict (regardless the casing). So, it throws an error and import stops. At least under Windows. This might be one thing to take into account. As Maven project is plain simple, even in Eclipse.

**Comment by codecracker2014** [comment]
Making xdoc-report(https://github.com/opensagres/xdocreport) compatible with OpenPDF with #333

**Comment by srbala** [comment]
> Making xdoc-report(https://github.com/opensagres/xdocreport) compatible with OpenPDF with #333

@codecracker2014 Going backwards is not a good option, might be good to update xdoc-report

**Comment by codecracker2014** [comment]
@andreasrosdal, @srbala  there are around 160 open source projects listed on maven (https://mvnrepository.com/artifact/com.lowagie/itext) which are using itext 2, if we can keep backward compatibility it would be really easy for them to migrate. 
Regarding https://github.com/LibrePDF/OpenPDF/pull/333#issuecomment-580730527:
Pull request for backward compatibility have been already merged with #210. Java 8 generics is not done yet fully, i would suggest to do it in future versions. 

I also tried to do changes in xdoc-reports instead of OpenPDF, there are lot of changes needs to be done as compared to OpenPDF change. Also that will make OpenPDF compatible to just xdoc-report, lot of other projects will still be remaining.

https://github.com/opensagres/xdocreport/issues/387
