### ISSUE TITLE
Exception writing font to PDF file

### ISSUE THREAD

**Issue by ducnv82** [LibrePDF/OpenPDF#211]
Using
```
        try (OutputStream outputStream = response.getOutputStream();
             Document document = new Document();
             PdfWriter writer = PdfWriter.getInstance(document, outputStream)) {
            writer.setFullCompression();
```

Then I have the exception
```
Jul 31, 2019 3:36:14 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at com.lowagie.text.pdf.TrueTypeFontUnicode.compare(TrueTypeFontUnicode.java:376)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.lowagie.text.pdf.TrueTypeFontUnicode.writeFont(TrueTypeFontUnicode.java:393)
	at com.lowagie.text.pdf.FontDetails.writeFont(FontDetails.java:317)
	at com.lowagie.text.pdf.PdfWriter.addSharedObjectsToBody(PdfWriter.java:1236)
	at com.lowagie.text.pdf.PdfWriter.close(PdfWriter.java:1170)
```

If I revert the try-with-resources, then all is ok.
Version: LibrePDF 1.3.0
Latets Oracle Java 8 on macOS

**Comment by andreasrosdal** [comment]
Thanks for reporting. Pull request welcome.

**Comment by andreasrosdal** [comment]
@asturio  Can you please look at this? It looks related to the recent font additions?

**Comment by andreasrosdal** [comment]
@ducnv82 Can you please try to reproduce the problem on the 'bug_211' branch:
https://github.com/LibrePDF/OpenPDF/tree/bug_211

I have added a commit here: https://github.com/LibrePDF/OpenPDF/commit/4ae6f87eee7264cc363291a078e94014074936a9

**Comment by ducnv82** [comment]
Hi @andreasrosdal , thank you for your quick actions. I applied, but I got another exception:
```
        java.lang.NullPointerException
	at com.lowagie.text.pdf.TrueTypeFontUnicode.getCIDFontType2(TrueTypeFontUnicode.java:335)
	at com.lowagie.text.pdf.TrueTypeFontUnicode.writeFont(TrueTypeFontUnicode.java:464)
	at com.lowagie.text.pdf.FontDetails.writeFont(FontDetails.java:323)
	at com.lowagie.text.pdf.PdfWriter.addSharedObjectsToBody(PdfWriter.java:1236)
	at com.lowagie.text.pdf.PdfWriter.close(PdfWriter.java:1170)
```

**Comment by ducnv82** [comment]
The fonts I use:
```
            final Font notosans = getFont("notosans", IDENTITY_H, true);
            final Font notosansBold = getFont("notosans-bold", IDENTITY_H, true);
```

**Comment by andreasrosdal** [comment]
@ducnv82 Can you please submit complete code to reproduce this problem?

**Comment by ducnv82** [comment]
I am sorry, I can't. My company product. It only uses 2 fonts: notosans, notosansBold.
Thank you.

**Comment by andreasrosdal** [comment]
I added a new commit to the 'bug_211' branch. Can you please try that?

@ducnv82 Maybe you can try to create a good fix yourself?  :)

**Comment by ducnv82** [comment]
Hi @andreasrosdal , just FYI-new exception:
```
java.lang.NullPointerException
	at com.lowagie.text.pdf.TrueTypeFontUnicode.filterCmapMetrics(TrueTypeFontUnicode.java:271)
	at com.lowagie.text.pdf.TrueTypeFontUnicode.getToUnicode(TrueTypeFontUnicode.java:216)
	at com.lowagie.text.pdf.TrueTypeFontUnicode.writeFont(TrueTypeFontUnicode.java:468)
	at com.lowagie.text.pdf.FontDetails.writeFont(FontDetails.java:274)
	at com.lowagie.text.pdf.PdfWriter.addSharedObjectsToBody(PdfWriter.java:1236)
	at com.lowagie.text.pdf.PdfWriter.close(PdfWriter.java:1170)
```
Thank you for your time :)
Best regards

**Comment by andreasrosdal** [comment]
@ducnv82  Can you please create a minimal example in Java, where this problem can be reproduced? Just create a new Java class with enough code to reproduce the problem. That means loading the notosans font, and creating a simple PDF file.

**Comment by ducnv82** [comment]
Hi @andreasrosdal , try this:
```
        try (Document document = new Document();
             PdfWriter writer = PdfWriter.getInstance(document, response.getOutputStream())) {
            writer.setFullCompression();

            registerDirectory("D:\\temp\\fonts");

            final Font notosans = getFont("notosans", IDENTITY_H, true);
            final Font notosansBold = getFont("notosans-bold", IDENTITY_H, true);

            response.setContentType("application/pdf");
            response.setHeader("Content-Disposition", " attachment; filename=\"File.pdf\"");
            response.setHeader("Content-Type", "application/pdf");

            document.open();

            document.add(new Paragraph("paragraph 1", notosans));
            document.add(new Paragraph("paragrapth 2", notosansBold));
        }
```
I downloaded NotoSans-Bold.ttf, NotoSans-BoldItalic.ttf, NotoSans-Italic.ttf, NotoSans-Regular.ttf and put in D:\temp\fonts

**Comment by andreasrosdal** [comment]
The example you provided isn't valid Jaca code. 
Please provide a complete, working and compiling Java class.

**Comment by ducnv82** [comment]
Hi @andreasrosdal :
```
    public static void main(final String[] args) throws IOException {
        try (OutputStream outputStream = new FileOutputStream("D:\\temp\\file.pdf");
             Document document = new Document();
             PdfWriter writer = PdfWriter.getInstance(document, outputStream)) {

            writer.setFullCompression();

            registerDirectory("D:\\temp\\fonts");

            final Font notosans = getFont("notosans", IDENTITY_H, true);
            final Font notosansBold = getFont("notosans-bold", IDENTITY_H, true);

            document.open();

            document.add(new Paragraph("paragraph 1", notosans));
            document.add(new Paragraph("paragraph 2", notosansBold));
        }
    }
```
results in NullPointerException:
```
Exception in thread "main" java.lang.NullPointerException
	at com.lowagie.text.pdf.TrueTypeFontUnicode.filterCmapMetrics(TrueTypeFontUnicode.java:271)
	at com.lowagie.text.pdf.TrueTypeFontUnicode.getToUnicode(TrueTypeFontUnicode.java:216)
	at com.lowagie.text.pdf.TrueTypeFontUnicode.writeFont(TrueTypeFontUnicode.java:468)
	at com.lowagie.text.pdf.FontDetails.writeFont(FontDetails.java:274)
	at com.lowagie.text.pdf.PdfWriter.addSharedObjectsToBody(PdfWriter.java:1236)
	at com.lowagie.text.pdf.PdfWriter.close(PdfWriter.java:1170)
```
Code runs ok:
```
    public static void main(final String[] args) throws IOException {
        OutputStream outputStream = new FileOutputStream("D:\\temp\\file.pdf");
        Document document = new Document();
        PdfWriter writer = PdfWriter.getInstance(document, outputStream);

        try {
            writer.setFullCompression();

            registerDirectory("D:\\temp\\fonts");

            final Font notosans = getFont("notosans", IDENTITY_H, true);
            final Font notosansBold = getFont("notosans-bold", IDENTITY_H, true);

            document.open();

            document.add(new Paragraph("paragraph 1", notosans));
            document.add(new Paragraph("paragraph 2", notosansBold));
        } finally {
            if (document.isOpen()) {
                document.close();
            }
            writer.close();
            outputStream.close();
        }
    }
```

**Comment by ducnv82** [comment]
Hi @andreasrosdal , only need to remove PdfWriter writer = PdfWriter.getInstance(document, outputStream) from the try-with-resources block, then it is ok, I have tested with OpenPDF 1.3.0
So, is 1.3.1 needed? or can it be reverted?
Thank you

**Comment by andreasrosdal** [comment]
@asturio @wiktor-k @daviddurand  Can you please help here? The above code can reproduce the problem. I'm unsure of the best solution.

**Comment by asturio** [comment]
I'll take a look at it.

**Comment by sixdouglas** [comment]
@ducnv82 : can you check with the latest version if the bug is still present?
I can't manage to reproduce it.
Thank you

**Comment by ducnv82** [comment]
Hi @sixdouglass, still it is

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

import static com.lowagie.text.FontFactory.getFont;
import static com.lowagie.text.FontFactory.registerDirectory;
import static com.lowagie.text.pdf.BaseFont.IDENTITY_H;

public class Utils {
    public static void main(final String[] args) throws IOException {
        try (OutputStream outputStream = new FileOutputStream("D:\\temp\\file.pdf");
             Document document = new Document();
             PdfWriter writer = PdfWriter.getInstance(document, outputStream)) {

            writer.setFullCompression();

            registerDirectory("D:\\temp\\fonts");

            final Font notosans = getFont("notosans", IDENTITY_H, true);
            final Font notosansBold = getFont("notosans-bold", IDENTITY_H, true);

            document.open();

            document.add(new Paragraph("paragraph 1", notosans));
            document.add(new Paragraph("paragraph 2", notosansBold));
        }
    }
}

**Comment by sixdouglas** [comment]
@ducnv82: I'm puzzled here. I can't get to reproduce this bug. 
Looking at the Stack-trace it looks like the font you've downloaded is/are no good. 
In fact, the failing function is called when OpenPdf includes a subset of the desired font in the output PDF. I can't get a NullPointerException in this function.
Maybe you can try to re-download them?
I guess, you've checked the directories existence, did you try with relative path? I'm on linux and it works well with both relative and absolute paths.

**Comment by andreasrosdal** [comment]
I'm able to reproduce this on Windows, using the code from @ducnv82.

**Comment by andreasrosdal** [comment]
@ducnv82 Can you please check if the problem is solved for you now, in the latest version of the master branch?

**Comment by ducnv82** [comment]
Hi all, I got the error Caused by: com.lowagie.text.ExceptionConverter: The document is not open.

**Comment by sixdouglas** [comment]
@ducnv82 can you give me some more specifics? code, full stack?

**Comment by ducnv82** [comment]
Hi @sixdouglas , I cannot reproduce with the above simple Java app Utils, but my project throws exception 
```
 java.lang.RuntimeException: The document is not open.
	at com.lowagie.text.pdf.PdfWriter.getDirectContent(PdfWriter.java:710)
	at com.lowagie.text.pdf.PdfDocument.isPageEmpty(PdfDocument.java:2308)
	at com.lowagie.text.pdf.PdfDocument.newPage(PdfDocument.java:857)
	at com.lowagie.text.pdf.PdfDocument.close(PdfDocument.java:816)
	at com.lowagie.text.Document.close(Document.java:452)
```
I am sorry that I could not give more my project source code. Thank you and best regards.

**Comment by sixdouglas** [comment]
@ducnv82 can you tell if the pdf gets generated?

**Comment by ducnv82** [comment]
@sixdouglas : yes, but it misses the last page, only 2 pages. Removing PdfWriter writer = PdfWriter.getInstance(document, outputStream) from try-with-resources block (before writer.setFullCompression(); in the below open bracket), then it generates fully 3 pages.

**Comment by sixdouglas** [comment]
@ducnv82: Is that the expected result? Do you still have the exception?
I have the impression that when using try with resources and multiple elements in it, java closes them in the creation order when I would have expected the reverse order. So, in deed, moving the writer out of it would be a solution. 
Do not hesitate to tell us if we can close this issue. 😉

**Comment by ducnv82** [comment]
Thanks, @sixdouglas . I will use finally in this case because I want to close PrintWriter also. But in other tutorials of iText, PrintWriter is not closed also, only Document is closed.

**Comment by mkl-public** [comment]
Just to explain why with code like this problems are extremely likely to occur:

    try (   OutputStream outputStream = new FileOutputStream("D:\\temp\\file.pdf");
            Document document = new Document();
            PdfWriter writer = PdfWriter.getInstance(document, outputStream)) {

        ...
    }

This eventually calls the respective `close` methods of first the `PdfWriter`, then the `Document`, then the `OutputStream`.

**But `PdfWriter.close()` must not be called before `Document.close()`!**

If you look into `PdfWriter.getInstance()`, you'll see that a `PdfDocument` is created there and registered as listener of the `Document`; furthermore, a `PdfWriter` is created and registered as writer of the `PdfDocument`.

If you inspect what happens when closing the `Document`, you'll see that the `Document` closes its listeners, i.e. here the `PdfDocument`.

If you inspect what happens when closing the `PdfDocument`, you'll see that it first does some final writes (store waiting floating images, trigger the `onCloseDocument` page event, write outlines, ...) to its writer, the `PdfWriter`, and then closes the writer.

*Thus, if (as in the code above) first the `PdfWriter` is closed and thereafter the `Document`, **then all these pending final writes of `PdfDocument.close()` target an already closed `PdfWriter`!***

Essentially it is an anti-pattern to close the `PdfWriter` at all from anywhere else but from `PdfDocument.close()`. In particular making `PdfWriter` a `Closable` in commit 67728975b5b4ae9143bd408728d1e8988a6281de gave completely wrong signals to the users.

**Comment by sixdouglas** [comment]
@mkl-public : thanks for these clear explanations. I’m wandering what is the pattern around the PDF Writer. This is not the subject of this thread but if you could point me to some explanations I would be thankful.

**Comment by mkl-public** [comment]
@sixdouglas Concerning the patterns around `PdfWriter` - As far as I know (only Bruno Lowagie and maybe Paulo Soares can tell for sure) iText originally was meant to have a document abstraction upfront (our `Document`) to send generic document components to. To this abstraction you could register listeners (yes, plural) which created concrete document files from the input in parallel, e.g. for the same inputs a HTML (via `HtmlWriter`), a PDF (via `PdfWriter`), and a RTF (via `RtfWriter` or later `RtfWriter2`).

In particular the `Document` was **the only** object user code was meant to work with and eventually to `close`.

As time was passing, though, more and more PDF specific features were implemented, soon requiring user code to explicitly address the `PdfWriter`; the alternative listeners, `RtfWriter` / `RtfWriter2`, `HtmlWriter`, and probably others I don't know, eventually were so much out of sync that iText essentially became a PDF only library with a weird, inconsequential architecture.

In iText 5 the PDF-only character officially was accepted by discontinuing the RTF and HTML related code, see https://stackoverflow.com/a/1893520/1729265; OpenPdf also restricted itself to the PDF parts. Nonetheless the inconsequential architecture remained in both cases and has caused many errors and has given rise to many questions ever since.

Concerning the *patterns around the PDF Writer*, therefore - don't try too hard to find them, the historic base pattern does not make sense anymore, and everything else has been added where it was easiest to add without overhauling that base architecture.

iText 7 eventually dropped all that legacy and redesigned the API for a PDF library. But as it contains many classes with similar names as in earlier iText incarnations (there again are `PdfReader`, `PdfWriter`, `PdfDocument`, `Document`, ...,  albeit each of them now having a sensible function in the context of a PDF only library), making it sometimes hard for people switching from the pre-v7 to the v7 API because they bring old habits along.

**Comment by sixdouglas** [comment]
@mkl-public: Thanks for this clear explanation and to be there to still have this in mind 😉.
