### ISSUE TITLE
PdfPCell background color ignoring alpha channel of an rgba

### ISSUE THREAD

**Issue by alaingaudreau** [LibrePDF/OpenPDF#276]
Is it expected behavior for PdfPCell to ignore the alpha channel value when you setBackgroundColor with a Color(r,g,b,a)?

I haven't seen anything in the docs/javadocs for this class regarding the alpha channel.

**Comment by razilein** [comment]
https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfContentByte.java#L2262

I've found this. The alpha channel is ignored, because it's value is not delivered at this point.

The alpha channel should be delivered to this method:
https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfContentByte.java#L2166

But I don't know how to set this. I've found that there is the parameter "S" which is for transparency.

See https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf
on page 347 (Table 144)

Maybe someone else can help with this example:

```java
    private static void cellWithRgb(Document doc) {
        PdfPCell redCell = new PdfPCell(new Paragraph("Red"));
        redCell.setBackgroundColor(new Color(255, 0, 0, 50));
        
        PdfPCell greenCell = new PdfPCell(new Paragraph("Green"));
        greenCell.setBackgroundColor(new Color(0, 255, 0, 100));
        
        PdfPCell blueCell = new PdfPCell(new Paragraph("Blue"));
        blueCell.setBackgroundColor(new Color(0, 204, 255, 255));

        final PdfPTable table = new PdfPTable(1);
        table.addCell(redCell);
        table.addCell(greenCell);
        table.addCell(blueCell);

        doc.add(table);
    }
```

**Comment by sixdouglas** [comment]
Here you have an example of the ContentByte in use:
https://github.com/LibrePDF/OpenPDF/blob/master/pdf-toolbox/src/test/java/com/lowagie/examples/directcontent/colors/Transparency.java
Maybe you can manage using this for the background color.

**Comment by mkl-public** [comment]
Related: https://stackoverflow.com/a/56954685/1729265

>Support for transparent cell background colors has been added in iText 5.5.7, more exactly in git commit 09ccaa728830a404e92fc3040dd3626198576fef.
>Depending on the exact version of iText you may try and use a `PdfPCellEvent `implementation instead of setting the background color with `setBackgroundColor`. In that implementation you'd have to first save the graphics state, then set a `PdfGState` with transparency, fill the cell rectangle with the color, and restore the graphics state again.

**Comment by sixdouglas** [comment]
@asturio maybe we need to build a release to make these changes available to all

**Comment by testn** [comment]
so this one should be closed?
