### ISSUE TITLE
Producer program + version number metadata is not populated in PDF's

### ISSUE THREAD

**Issue by chas678** [LibrePDF/OpenPDF#327]
Producer metadata not available.  Missing out on free marketing opportunity for this project :-D 
test was doing a PDF merge (merge 3 PDFS into 1) - no metadata available in the output.

**Comment by andreasrosdal** [comment]
Thanks for reporting. Pull request welcome.

**Comment by albfernandez** [comment]
Hi
I've submitted several pull request on this topic [here](https://github.com/LibrePDF/OpenPDF/pull/179) It's intentional to disable by default  wrinting any metadata (security reasons: we dont want to leak info to an attacker).
You can always call to document.addProducer() by yourself.

It's open for discussion of course.
