### ISSUE TITLE
Unicode Characters

### ISSUE THREAD

**Issue by Blackbilbao** [LibrePDF/OpenPDF#33]
Hi everyone,

i'm new to your repo. I'm trying to print a special unicode character \u25b2 which would be a triangle in the Times new Roman font...

unfortianaly it is ignroed when looking at the pdf
`
private static final Font NORMALFONT = new Font(Font.TIMES_ROMAN, 7, Font.NORMAL, Color.black);
`	
![image](https://user-images.githubusercontent.com/6515405/28062441-3defccce-662e-11e7-931c-37072f01651b.png)

and the result

![image](https://user-images.githubusercontent.com/6515405/28062467-51c6f646-662e-11e7-8777-c5812aab1b66.png)
where there should be this triangle before every number

Do i do something wrong here?

**Comment by andreasrosdal** [comment]
Sorry, I don't know the answer to this. Please share the solution here if you find out.

**Comment by asturio** [comment]
Hi there,

I just investigated this, and I think the problem is, that the Times Font in openpdf is quite old and doesn't contain unicode character.

There is 2 possible solutions for that:

- the easiest one should be to replace the font, but there is probably some issues with the license.
- the second one is to read the font from some where else, and embed that in the PDF.

I have some code here to try that in my fork 
https://github.com/asturio/OpenPDF/blob/test/unicode/openpdf/src/test/java/com/lowagie/text/pdf/UnicodePdfTest.java

Should I issue a pull request? There are also other tests for checking the Version number of openpdf.

**Comment by andreasrosdal** [comment]
Yes, please submit a pull-request.

**Comment by asturio** [comment]
@Blackbilbao, have you tried using a different font? I loaded my own, and it worked (see Test in the other comment).

**Comment by Blackbilbao** [comment]
I have treid diffrent fonts (external ones) at indeed it works with them...

**Comment by asturio** [comment]
Added https://github.com/LibrePDF/OpenPDF/pull/194
