### ISSUE TITLE
Order of objects in generated PDF file is not always consistent

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#98]
@pvandenbroucke reported in this issue: "A important issue is that visual generation doesn't guaranteed the objects order in the pdf file. I didn't find the root cause."
Details about the bug can also be found here: https://github.com/LibrePDF/OpenPDF/issues/86#issuecomment-416547183

Pull-request to reproduce the problem: https://github.com/LibrePDF/OpenPDF/pull/97

@pvandenbroucke Please supply more details if you have. This bug should get the highest priority to be fixed. Pull-requests welcome!

**Comment by pvandenbroucke** [comment]
From my analysis, the problem can happen when a visible signature is added. I added a loop in the unit test because it doesn't always occur. 

If you check the files in the comment, you can see that XObjects 43 and 47 are inverted.

IMO, the problem (or a part of it) is the used Map formXObjects in the class PdfWriter. The iteration order is not guaranteed.

**Comment by andreasrosdal** [comment]
I might have fixed this in the master branch now. The test is at least passing.
