### ISSUE TITLE
commons-io:commons-io has dependency scope conflict

### ISSUE THREAD

**Issue by HappyHacker123** [LibrePDF/OpenPDF#995]
**Describe the bug**
The issue arises due to conflicting scopes between the following dependencies in the project:

-   Direct Dependency: commons-io:commons-io scoped as **test**.
```
[INFO] +- commons-io:commons-io:jar:2.15.0:test (scope not updated to compile)
```
-   Transitive Dependency: commons-io:commons-io scoped as **compile** multiple places in the dependency tree.
```
[INFO] |  +- org.apache.xmlgraphics:fop-util:jar:2.9:compile
[INFO] |  |  +- (commons-io:commons-io:jar:2.15.0:compile - version managed from 2.11.0; omitted for duplicate)
[INFO] |  +- org.apache.xmlgraphics:fop-events:jar:2.9:compile
[INFO] |  |  +- (commons-io:commons-io:jar:2.15.0:compile - version managed from 2.11.0; omitted for duplicate)
...

```

When a transitive dependency has a scope set to compile, it indicates that the dependency is intended for usage both at compile time and runtime. 

Normally, Maven resolves scopes by selecting the widest scope among dependencies (i.e. compile over test), but treats directly declared scopes differently. In this scenario, the direct dependency's explicitly declared ***test*** scope takes precedence over the transitive dependency's intended ***compile*** scope. Consequently, the final scope of commons-io:commons-io is set to ***test*** scope, conflicting with the transitive dependecies' ***compile*** scope. Unexpected behavior or errors may surface when utilizing the transitive dependency's features in scenarios beyond testing.

**Expected behavior**
Align dependency scopes to ensure consistency and avoid conflicts. Consider updating the direct dependency's scope to accommodate the required functionality from the transitive dependency.

**Comment by andreasrosdal** [comment]
Thank you for this contribution to OpenPDF. However, I don't agree with this change, because commons-io should be an optional dependency, not a hard required dependency. Apache FOP is an optional dependency to OpenPDF.
I will therefore reject this pull request, please submit an updated pull request.

**Comment by HappyHacker123** [comment]
@andreasrosdal Thanks for your response. I understand that commons-io is not a hard required dependency. However, declaring it as an test scope dependency will cause scope conflict as i mentioned above. 

Do you think removing the commons-io dependency is acceptable? In this way, OpenPDF will use the dependency introduced by FOP. 

Or maybe setting the scope to compile but declare it as optional?

**Comment by andreasrosdal** [comment]
> Do you think removing the commons-io dependency is acceptable? In this way, OpenPDF will use the dependency introduced by FOP.

commons-io is currently in use in this test here:
https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/test/java/com/lowagie/text/pdf/fonts/AdvanceTypographyTest.java
Therefore the commons-io dependency is in fact in use in an OpenPDF test.

This is my current opinion on this:
* commons-io should not be a hard required dependency for OpenPDF, because we want to keep the number of dependencies as low as possible.
* commons-io is currently in use in multiple tests, for example AdvanceTypographyTest.

Given these constrains, I welcome pull requests to find a solution to this. Thank you!

**Comment by andreasrosdal** [comment]
Closing this. I don't think there is a need to change this at this time.
